name: Pack
description: Build application images using buildpacks with pack
author: https://github.com/vanstee
requirements:
  - pack
configuration:
  properties:
    build:
      type: object
      properties:
        image:
          type: string
      required:
        - image
      additionalProperties: false
  required:
    - build
  additionalProperties: false
